#pragma once
enum class ButtonType
{
	CREATE_RECTANGLE,
	CREATE_TRIANGLE,
	CREATE_CIRCLE,
	DRAG_AND_DROP,
	CHAGNE_FILL_COLOR_TYPE,
	CHANGE_OUTLINE_COLOR_TYPE,
	CHANGE_OUTLINE_THICKNESS_TYPE,
	THICKNESS_ONE,
	THICKNESS_TWO,
	THICKNESS_THREE,
	PURPLE_COLOR,
	YELLOW_COLOR,
	ORANGE_COLOR,
};

