#pragma once
enum class StateType
{
	DRAG_AND_DROP,
	ADD_RECTANGLE_TYPE,
	ADD_TRIANGLE_TYPE,
	ADD_CIRCLE_TYPE,
	CHAGNE_FILL_COLOR_TYPE,
	CHANGE_OUTLINE_COLOR_TYPE,
	CHANGE_OUTLINE_THICKNESS_TYPE,
};

